AWSTemplateFormatVersion: '2010-09-09'
Description: SportLinkCore dynamodb table.

Resources:
  UserDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SportLinkCore
      AttributeDefinitions:
        - AttributeName: EntityId
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
        - AttributeName: GeohashPrefix
          AttributeType: S
        - AttributeName: Day
          AttributeType: N
        - AttributeName: OwnerAccountId
          AttributeType: S
        - AttributeName: AccountId
          AttributeType: S
      KeySchema:
        - AttributeName: EntityId
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GeohashPrefix-Day-index
          KeySchema:
            - AttributeName: GeohashPrefix
              KeyType: HASH
            - AttributeName: Day
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: OwnerAccountId-index
          KeySchema:
            - AttributeName: OwnerAccountId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: AccountId-index
          KeySchema:
            - AttributeName: AccountId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5