// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	"context"

	"sportlink/api/application/matchrequest/usecases"
	domain "sportlink/api/domain/matchrequest"

	mock "github.com/stretchr/testify/mock"
)

// CreateMatchRequestUseCase is an autogenerated mock type for the CreateMatchRequestUseCase type
type CreateMatchRequestUseCase struct {
	mock.Mock
}

// Invoke provides a mock function with given fields: ctx, input
func (_m *CreateMatchRequestUseCase) Invoke(ctx context.Context, input usecases.CreateMatchRequestInput) (*domain.Entity, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 *domain.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.CreateMatchRequestInput) (*domain.Entity, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.CreateMatchRequestInput) *domain.Entity); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.CreateMatchRequestInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMatchRequestsUseCase is an autogenerated mock type for the FindMatchRequestsUseCase type
type FindMatchRequestsUseCase struct {
	mock.Mock
}

// Invoke provides a mock function with given fields: ctx, ownerAccountID
func (_m *FindMatchRequestsUseCase) Invoke(ctx context.Context, ownerAccountID string) ([]domain.Entity, error) {
	ret := _m.Called(ctx, ownerAccountID)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 []domain.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Entity, error)); ok {
		return rf(ctx, ownerAccountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Entity); ok {
		r0 = rf(ctx, ownerAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSentMatchRequestsUseCase is an autogenerated mock type for the FindSentMatchRequestsUseCase type
type FindSentMatchRequestsUseCase struct {
	mock.Mock
}

// Invoke provides a mock function with given fields: ctx, requesterAccountID, statuses
func (_m *FindSentMatchRequestsUseCase) Invoke(ctx context.Context, requesterAccountID string, statuses []domain.Status) ([]domain.Entity, error) {
	ret := _m.Called(ctx, requesterAccountID, statuses)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 []domain.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.Status) ([]domain.Entity, error)); ok {
		return rf(ctx, requesterAccountID, statuses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.Status) []domain.Entity); ok {
		r0 = rf(ctx, requesterAccountID, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []domain.Status) error); ok {
		r1 = rf(ctx, requesterAccountID, statuses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMatchRequestStatusUseCase is an autogenerated mock type for the UpdateMatchRequestStatusUseCase type
type UpdateMatchRequestStatusUseCase struct {
	mock.Mock
}

// Invoke provides a mock function with given fields: ctx, input
func (_m *UpdateMatchRequestStatusUseCase) Invoke(ctx context.Context, input usecases.UpdateMatchRequestStatusInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.UpdateMatchRequestStatusInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
