AWSTemplateFormatVersion: '2010-09-09'
Description: SportLinkCore dynamodb table.

Resources:
  UserDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SportLinkCore
      AttributeDefinitions:
        - AttributeName: EntityId
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: EntityId
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5