AWSTemplateFormatVersion: '2010-09-09'
Description: Template para crear una cola SQS

Resources:
  MySQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "sportlink-news"
      VisibilityTimeout: 60
      MessageRetentionPeriod: 345600
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDeadLetterQueue.Arn
        maxReceiveCount: 5

  MyDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "sportlink-news-dlq"
      MessageRetentionPeriod: 1209600

Outputs:
  SQSQueueUrl:
    Description: URL de la cola SQS
    Value: !Ref MySQSQueue
  SQSQueueArn:
    Description: ARN de la cola SQS
    Value: !GetAtt MySQSQueue.Arn
  DeadLetterQueueArn:
    Description: ARN de la cola de mensajes fallidos (DLQ)
    Value: !GetAtt MyDeadLetterQueue.Arn
