// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase[T any, O any] struct {
	mock.Mock
}

// Invoke provides a mock function with given fields: ctx, input
func (_m *UseCase[T, O]) Invoke(ctx context.Context, input T) (*O, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 *O
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (*O, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) *O); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*O)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase[T any, O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase[T, O] {
	mock := &UseCase[T, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
