// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	"context"
	matchoffer "sportlink/api/domain/matchoffer"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// SaveAll provides a mock function with given fields: ctx, entities
func (_m *Repository) SaveAll(ctx context.Context, entities []matchoffer.Entity) (int, error) {
	ret := _m.Called(ctx, entities)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []matchoffer.Entity) (int, error)); ok {
		return rf(ctx, entities)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []matchoffer.Entity) int); ok {
		r0 = rf(ctx, entities)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []matchoffer.Entity) error); ok {
		r1 = rf(ctx, entities)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, query
func (_m *Repository) Find(ctx context.Context, query matchoffer.DomainQuery) (matchoffer.Page, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 matchoffer.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, matchoffer.DomainQuery) (matchoffer.Page, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, matchoffer.DomainQuery) matchoffer.Page); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(matchoffer.Page)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, matchoffer.DomainQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, offerID
func (_m *Repository) Delete(ctx context.Context, offerID string) error {
	ret := _m.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, offerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, entity
func (_m *Repository) Save(ctx context.Context, entity matchoffer.Entity) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, matchoffer.Entity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
