// Code generated by "stringer -type=Category"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unranked-0]
	_ = x[L1-2]
	_ = x[L2-3]
	_ = x[L3-4]
	_ = x[L4-5]
	_ = x[L5-6]
	_ = x[L6-7]
	_ = x[L7-8]
	_ = x[MaxCategory-9]
}

const (
	_Category_name_0 = "Unranked"
	_Category_name_1 = "L1L2L3L4L5L6L7MaxCategory"
)

var (
	_Category_index_1 = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 25}
)

func (i Category) String() string {
	switch {
	case i == 0:
		return _Category_name_0
	case 2 <= i && i <= 9:
		i -= 2
		return _Category_name_1[_Category_index_1[i]:_Category_index_1[i+1]]
	default:
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
