// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"sportlink/api/application/auth/service"
)

// JWTService is an autogenerated mock type for the JWTService type
type JWTService struct {
	mock.Mock
}

// Generate provides a mock function with given fields: accountID
func (_m *JWTService) Generate(accountID string) (string, error) {
	ret := _m.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(accountID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(accountID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Parse provides a mock function with given fields: token
func (_m *JWTService) Parse(token string) (*service.AccessTokenClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *service.AccessTokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*service.AccessTokenClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *service.AccessTokenClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AccessTokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTService creates a new instance of JWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTService {
	m := &JWTService{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}
