// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	"context"
	match "sportlink/api/domain/match"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, entity
func (_m *Repository) Save(ctx context.Context, entity match.Entity) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, match.Entity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, query
func (_m *Repository) Find(ctx context.Context, query match.DomainQuery) ([]match.Entity, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []match.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, match.DomainQuery) ([]match.Entity, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, match.DomainQuery) []match.Entity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]match.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, match.DomainQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, accountID, matchID
func (_m *Repository) FindByID(ctx context.Context, accountID string, matchID string) (*match.Entity, error) {
	ret := _m.Called(ctx, accountID, matchID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *match.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*match.Entity, error)); ok {
		return rf(ctx, accountID, matchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *match.Entity); ok {
		r0 = rf(ctx, accountID, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*match.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accountID, matchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
