// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	account "sportlink/api/domain/account"

	mock "github.com/stretchr/testify/mock"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Check provides a mock function with given fields: entity
func (_m *Validator) Check(entity account.Entity) []error {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 []error
	if rf, ok := ret.Get(0).(func(account.Entity) []error); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
