// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	common "sportlink/api/domain/common"
	matchannouncement "sportlink/api/domain/matchannouncement"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// QueryParser is an autogenerated mock type for the QueryParser type
type QueryParser struct {
	mock.Mock
}

// ParseCategories provides a mock function with given fields: categoriesQuery
func (_m *QueryParser) ParseCategories(categoriesQuery string) ([]common.Category, error) {
	ret := _m.Called(categoriesQuery)

	if len(ret) == 0 {
		panic("no return value specified for ParseCategories")
	}

	var r0 []common.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]common.Category, error)); ok {
		return rf(categoriesQuery)
	}
	if rf, ok := ret.Get(0).(func(string) []common.Category); ok {
		r0 = rf(categoriesQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(categoriesQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseDate provides a mock function with given fields: dateQuery
func (_m *QueryParser) ParseDate(dateQuery string) (time.Time, error) {
	ret := _m.Called(dateQuery)

	if len(ret) == 0 {
		panic("no return value specified for ParseDate")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (time.Time, error)); ok {
		return rf(dateQuery)
	}
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(dateQuery)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dateQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseLocation provides a mock function with given fields: country, province, locality
func (_m *QueryParser) ParseLocation(country, province, locality string) *matchannouncement.Location {
	ret := _m.Called(country, province, locality)

	if len(ret) == 0 {
		panic("no return value specified for ParseLocation")
	}

	var r0 *matchannouncement.Location
	if rf, ok := ret.Get(0).(func(string, string, string) *matchannouncement.Location); ok {
		r0 = rf(country, province, locality)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*matchannouncement.Location)
		}
	}

	return r0
}

// ParseSports provides a mock function with given fields: sportsQuery
func (_m *QueryParser) ParseSports(sportsQuery string) ([]common.Sport, error) {
	ret := _m.Called(sportsQuery)

	if len(ret) == 0 {
		panic("no return value specified for ParseSports")
	}

	var r0 []common.Sport
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]common.Sport, error)); ok {
		return rf(sportsQuery)
	}
	if rf, ok := ret.Get(0).(func(string) []common.Sport); ok {
		r0 = rf(sportsQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Sport)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sportsQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseStatuses provides a mock function with given fields: statusesQuery
func (_m *QueryParser) ParseStatuses(statusesQuery string) ([]matchannouncement.Status, error) {
	ret := _m.Called(statusesQuery)

	if len(ret) == 0 {
		panic("no return value specified for ParseStatuses")
	}

	var r0 []matchannouncement.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]matchannouncement.Status, error)); ok {
		return rf(statusesQuery)
	}
	if rf, ok := ret.Get(0).(func(string) []matchannouncement.Status); ok {
		r0 = rf(statusesQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]matchannouncement.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(statusesQuery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQueryParser creates a new instance of QueryParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryParser {
	mock := &QueryParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
