// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	matchannouncement "sportlink/api/domain/matchannouncement"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: query
func (_m *Repository) Find(query matchannouncement.DomainQuery) ([]matchannouncement.Entity, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []matchannouncement.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(matchannouncement.DomainQuery) ([]matchannouncement.Entity, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(matchannouncement.DomainQuery) []matchannouncement.Entity); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]matchannouncement.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(matchannouncement.DomainQuery) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: entity
func (_m *Repository) Save(entity matchannouncement.Entity) error {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(matchannouncement.Entity) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
