// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	"context"
	matchannouncement "sportlink/api/domain/matchannouncement"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, query
func (_m *Repository) Find(ctx context.Context, query matchannouncement.DomainQuery) (matchannouncement.Page, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 matchannouncement.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, matchannouncement.DomainQuery) (matchannouncement.Page, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, matchannouncement.DomainQuery) matchannouncement.Page); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(matchannouncement.Page)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, matchannouncement.DomainQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, entity
func (_m *Repository) Save(ctx context.Context, entity matchannouncement.Entity) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, matchannouncement.Entity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
